[package]
name = "datafusion-test"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
datafusion = { version = "50.0.0", default-features = false, features = ["parquet"] }
arrow = "56.1"
env_logger = "0.11"